services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - PYTHONUNBUFFERED=1
      - JWT_SECRET_KEY=some_super_secret_key
      - JWT_ACCESS_COOKIE_NAME=access_token_cookie

  frontend:
    build: ./frontend
    container_name: frontend-ui
    ports:
      - "80:80"
    depends_on:
      - backend
